### ISSUE TITLE
Can't compile with MacOS 10.13.6

### ISSUE THREAD

**Issue by apuignav** [ClickHouse/clickhouse-odbc#293]
Following the README.md instructions with iODBC with latest `master`, compile fails with 

```
clickhouse-odbc/driver/attributes.h:98:30: error: call to unavailable function 'visit': introduced in macOS 10.14
```

Is the minimum macOS version 10.14?

**Comment by traceon** [comment]
Yes, looks like. https://stackoverflow.com/questions/52310835/xcode-10-call-to-unavailable-function-stdvisit/53868971

**Comment by traceon** [comment]
You can probably try Homebrew's (recent) versions of gcc or clang.
